include ../../../dir_list.mk

OVERLAY     = base
BOARD	    = zcu208

RTL_SRC    += $(RTL_DIR)/adc_capture.v
RTL_SRC    += $(BEDROCK_DIR)/dsp/reg_tech_cdc.v
RTL_SRC    += $(BEDROCK_DIR)/dsp/trigger.v
RTL_SRC    += $(RTL_DIR)/axil_rf_control.v
RTL_SRC    += $(RTL_DIR)/axil_csr.v
RTL_SRC    += $(RTL_DIR)/pulse_gen.v
RTL_SRC    += $(RTL_DIR)/axil_wave_gen.v
RTL_SRC    += $(RTL_DIR)/wave_gen.v

include $(SCRIPT_DIR)/common.mk
