stages:
  - prepare
  - test
  - synthesis

variables:
  XILINX_VIVADO: /non-free/Xilinx/Vivado_and_Vitis/2022.1/Vivado/2022.1
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: normal

image: mohs.dhcp.lbl.gov/xilinx_env_trixie

flake8:
  stage: test
  script:
    - flake8 mimo_mts designs

rtl_test:
  before_script:
    - apt-get install verilator
    - pip install -r designs/ip/tb/requirements.txt
    - cd designs/ip/tb
  stage: test
  script:
    - make RANDOM_SEED=1747031728

bitfile_synthesis_zcu216:
  before_script:
    - cd designs/ZCU216/${OVERLAY}
  stage: synthesis
  timeout: 3h
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH && make all
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    when: always
    paths:
      - designs/ZCU216/${OVERLAY}/${OVERLAY}.bit
      - designs/ZCU216/${OVERLAY}/${OVERLAY}.hwh
      # - designs/ZCU216/${OVERLAY}/${OVERLAY}.xsa
      - designs/ZCU216/${OVERLAY}/_xilinx/${OVERLAY}/${OVERLAY}.runs/{synth_1,impl_1}/*.log
      - designs/ZCU216/${OVERLAY}/_xilinx/${OVERLAY}/${OVERLAY}.runs/{synth_1,impl_1}/*.rpt
  parallel:
    matrix:
      - OVERLAY: [mimo_mts]

bitfile_synthesis_208:
  before_script:
    - cd designs/${BOARD}/${OVERLAY}
  stage: synthesis
  timeout: 3h
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH && make all
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    when: always
    paths:
      - designs/${BOARD}/${OVERLAY}/${OVERLAY}.bit
      - designs/${BOARD}/${OVERLAY}/${OVERLAY}.hwh
      # - designs/${BOARD}/${OVERLAY}/${OVERLAY}.xsa
      - designs/${BOARD}/${OVERLAY}/_xilinx/${OVERLAY}/${OVERLAY}.runs/{synth_1,impl_1}/*.log
      - designs/${BOARD}/${OVERLAY}/_xilinx/${OVERLAY}/${OVERLAY}.runs/{synth_1,impl_1}/*.rpt
  parallel:
    matrix:
      - OVERLAY: [als_llrf_mts, mimo_mts]
        BOARD: [ZCU208, LBL208]
