stages:
  - prepare
  - test
  - synthesis

default:
  tags:
    - xilinx-bookworm

variables:
  XILINX_VIVADO: /non-free/Xilinx/Vivado_and_Vitis/2022.1/Vivado/2022.1
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: normal

image: mohs.dhcp.lbl.gov/xilinx_env_bookworm

flake8:
  stage: test
  script:
    - flake8 mimo_mts/

rtl_test:
  before_script:
    - apt-get install verilator
    - pip install -r requirements.txt
    - cd boards/ip/tb
  stage: test
  script:
    - make SIM=icarus

bitfile_synthesis_zcu208:
  before_script:
    - cd boards/ZCU208/${OVERLAY} && ls /non-free
  stage: synthesis
  timeout: 3h
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH && make all
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - boards/ZCU208/${OVERLAY}/${OVERLAY}.bit
      - boards/ZCU208/${OVERLAY}/${OVERLAY}.hwh
      - boards/ZCU208/${OVERLAY}/${OVERLAY}.xsa
      - boards/ZCU208/${OVERLAY}/_xilinx/${OVERLAY}/${OVERLAY}.runs/{synth_1,impl_1}/*.log
      - boards/ZCU208/${OVERLAY}/_xilinx/${OVERLAY}/${OVERLAY}.runs/{synth_1,impl_1}/*.rpt
  parallel:
    matrix:
      - OVERLAY: [config_evr, als_llrf_mts]

.bitfile_synthesis_zcu216:
  before_script:
    - cd boards/ZCU216/${OVERLAY} && ls /non-free
  stage: synthesis
  timeout: 3h
  script:
    - make clean && PATH=$XILINX_VIVADO/bin:$PATH && make all
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 4 weeks
    paths:
      - boards/ZCU216/${OVERLAY}/${OVERLAY}.bit
      - boards/ZCU216/${OVERLAY}/${OVERLAY}.hwh
      - boards/ZCU216/${OVERLAY}/${OVERLAY}.xsa
      - boards/ZCU216/${OVERLAY}/_xilinx/${OVERLAY}/${OVERLAY}.runs/{synth_1,impl_1}/*.log
      - boards/ZCU216/${OVERLAY}/_xilinx/${OVERLAY}/${OVERLAY}.runs/{synth_1,impl_1}/*.rpt
  parallel:
    matrix:
      - OVERLAY: [mimo_mts]
