include ../../../dir_list.mk

OVERLAY     = mimo_mts
BOARD       = zcu208
RTL_SRC     = $(RTL_DIR)/adc_capture.v
RTL_SRC	   += $(RTL_DIR)/dac_streamer.v
RTL_SRC	   += $(BEDROCK_DIR)/dsp/freq_count.v
RTL_SRC	   += $(BEDROCK_DIR)/dsp/freq_gcount.v
RTL_SRC	   += $(RTL_DIR)/axil_rf_control.v
RTL_SRC	   += $(RTL_DIR)/axil_csr.v
RTL_SRC	   += $(RTL_DIR)/pulse_gen.v

include $(SCRIPT_DIR)/common.mk
