include ../../../dir_list.mk

OVERLAY     = mimo_mts
BOARD       = zcu208
RTL_SRC     = $(IP_DIR)/rtl/adc_capture.v
RTL_SRC	   += $(IP_DIR)/rtl/dac_streamer.v
RTL_SRC	   += $(IP_DIR)/rtl/freq_count.v

include $(SCRIPT_DIR)/common.mk
